name: Build and Unit Test

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.22.1'
    - name: install ubuntu dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y lsb-release
        python3 -m pip install protobuf
    - name: Cache protobuf
      id: cache-protobuf
      uses: actions/cache@v2
      env:
        cache-name: protobuf
      with:
        path: protobuf-3.20.2
        key: protobuf-3.20.2-${{ runner.os }}-v2
    - name: Download protobuf
      uses: actions/checkout@v2
      if: steps.cache-protobuf.outputs.cache-hit != 'true'
      with:
        repository: "protocolbuffers/protobuf"
        ref: "3.20.2"
        path: protobuf-3.20.2
        submodules: recursive
    - name: Build protobuf
      id: build-protobuf
      if: steps.cache-protobuf.outputs.cache-hit != 'true'
      working-directory: protobuf-3.20.2
      run: |
        mkdir build && cd build
        cmake .. -Dprotobuf_BUILD_TESTS=OFF
        make
    - name: install protobuf
      working-directory: protobuf-3.20.2/build
      run: |
        sudo make install
